# ~/.dotfiles/.config/mpd/mpd.conf

music_directory    "~/arth/Music"
playlist_directory "~/arth/Music/mpd/playlists"
db_file            "~/arth/state/mpd/database"
log_file           "~/arth/state/mpd/log"
pid_file           "~/arth/state/mpd/pid"
state_file         "~/arth/state/mpd/state"
sticker_file       "~/arth/state/mpd/sticker.sql"

bind_to_address    "127.0.0.1"
port               "6600"

audio_output {
    type "osx"
    name "macOS Audio Output"
}

auto_update "yes"

